env:
  es2021: true
  node: true

extends: standard-with-typescript
overrides: []

parserOptions:
  project: tsconfig.json
  ecmaVersion: latest
  sourceType: module

rules: {
  "@typescript-eslint/explicit-function-return-type": off
}
